packages:
  github.com/nojyerac/semaphore/data:
    config:
      dir: ./mocks/data
      with-expecter: True
      resolve-type-alias: False
      issue-845-fix: True
      include-regex: "^(Source|DataEngine)$"
