// Code generated by mockery v2.53.6. DO NOT EDIT.

package data

import (
	context "context"

	data "github.com/nojyerac/semaphore/data"
	mock "github.com/stretchr/testify/mock"
)

// MockDataEngine is an autogenerated mock type for the DataEngine type
type MockDataEngine struct {
	mock.Mock
}

type MockDataEngine_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDataEngine) EXPECT() *MockDataEngine_Expecter {
	return &MockDataEngine_Expecter{mock: &_m.Mock}
}

// CreateFlag provides a mock function with given fields: ctx, flag
func (_m *MockDataEngine) CreateFlag(ctx context.Context, flag *data.FeatureFlag) (string, error) {
	ret := _m.Called(ctx, flag)

	if len(ret) == 0 {
		panic("no return value specified for CreateFlag")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *data.FeatureFlag) (string, error)); ok {
		return rf(ctx, flag)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *data.FeatureFlag) string); ok {
		r0 = rf(ctx, flag)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *data.FeatureFlag) error); ok {
		r1 = rf(ctx, flag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDataEngine_CreateFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFlag'
type MockDataEngine_CreateFlag_Call struct {
	*mock.Call
}

// CreateFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - flag *data.FeatureFlag
func (_e *MockDataEngine_Expecter) CreateFlag(ctx interface{}, flag interface{}) *MockDataEngine_CreateFlag_Call {
	return &MockDataEngine_CreateFlag_Call{Call: _e.mock.On("CreateFlag", ctx, flag)}
}

func (_c *MockDataEngine_CreateFlag_Call) Run(run func(ctx context.Context, flag *data.FeatureFlag)) *MockDataEngine_CreateFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*data.FeatureFlag))
	})
	return _c
}

func (_c *MockDataEngine_CreateFlag_Call) Return(_a0 string, _a1 error) *MockDataEngine_CreateFlag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDataEngine_CreateFlag_Call) RunAndReturn(run func(context.Context, *data.FeatureFlag) (string, error)) *MockDataEngine_CreateFlag_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFlag provides a mock function with given fields: ctx, id
func (_m *MockDataEngine) DeleteFlag(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFlag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDataEngine_DeleteFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFlag'
type MockDataEngine_DeleteFlag_Call struct {
	*mock.Call
}

// DeleteFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDataEngine_Expecter) DeleteFlag(ctx interface{}, id interface{}) *MockDataEngine_DeleteFlag_Call {
	return &MockDataEngine_DeleteFlag_Call{Call: _e.mock.On("DeleteFlag", ctx, id)}
}

func (_c *MockDataEngine_DeleteFlag_Call) Run(run func(ctx context.Context, id string)) *MockDataEngine_DeleteFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDataEngine_DeleteFlag_Call) Return(_a0 error) *MockDataEngine_DeleteFlag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDataEngine_DeleteFlag_Call) RunAndReturn(run func(context.Context, string) error) *MockDataEngine_DeleteFlag_Call {
	_c.Call.Return(run)
	return _c
}

// EvaluateFlag provides a mock function with given fields: ctx, flagID, userID, groupIDs
func (_m *MockDataEngine) EvaluateFlag(ctx context.Context, flagID string, userID string, groupIDs []string) (bool, error) {
	ret := _m.Called(ctx, flagID, userID, groupIDs)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateFlag")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) (bool, error)); ok {
		return rf(ctx, flagID, userID, groupIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) bool); ok {
		r0 = rf(ctx, flagID, userID, groupIDs)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []string) error); ok {
		r1 = rf(ctx, flagID, userID, groupIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDataEngine_EvaluateFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluateFlag'
type MockDataEngine_EvaluateFlag_Call struct {
	*mock.Call
}

// EvaluateFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - flagID string
//   - userID string
//   - groupIDs []string
func (_e *MockDataEngine_Expecter) EvaluateFlag(ctx interface{}, flagID interface{}, userID interface{}, groupIDs interface{}) *MockDataEngine_EvaluateFlag_Call {
	return &MockDataEngine_EvaluateFlag_Call{Call: _e.mock.On("EvaluateFlag", ctx, flagID, userID, groupIDs)}
}

func (_c *MockDataEngine_EvaluateFlag_Call) Run(run func(ctx context.Context, flagID string, userID string, groupIDs []string)) *MockDataEngine_EvaluateFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]string))
	})
	return _c
}

func (_c *MockDataEngine_EvaluateFlag_Call) Return(_a0 bool, _a1 error) *MockDataEngine_EvaluateFlag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDataEngine_EvaluateFlag_Call) RunAndReturn(run func(context.Context, string, string, []string) (bool, error)) *MockDataEngine_EvaluateFlag_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlagByID provides a mock function with given fields: ctx, id
func (_m *MockDataEngine) GetFlagByID(ctx context.Context, id string) (*data.FeatureFlag, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFlagByID")
	}

	var r0 *data.FeatureFlag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*data.FeatureFlag, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *data.FeatureFlag); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.FeatureFlag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDataEngine_GetFlagByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlagByID'
type MockDataEngine_GetFlagByID_Call struct {
	*mock.Call
}

// GetFlagByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDataEngine_Expecter) GetFlagByID(ctx interface{}, id interface{}) *MockDataEngine_GetFlagByID_Call {
	return &MockDataEngine_GetFlagByID_Call{Call: _e.mock.On("GetFlagByID", ctx, id)}
}

func (_c *MockDataEngine_GetFlagByID_Call) Run(run func(ctx context.Context, id string)) *MockDataEngine_GetFlagByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDataEngine_GetFlagByID_Call) Return(_a0 *data.FeatureFlag, _a1 error) *MockDataEngine_GetFlagByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDataEngine_GetFlagByID_Call) RunAndReturn(run func(context.Context, string) (*data.FeatureFlag, error)) *MockDataEngine_GetFlagByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlags provides a mock function with given fields: ctx
func (_m *MockDataEngine) GetFlags(ctx context.Context) ([]*data.FeatureFlag, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFlags")
	}

	var r0 []*data.FeatureFlag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*data.FeatureFlag, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*data.FeatureFlag); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*data.FeatureFlag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDataEngine_GetFlags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlags'
type MockDataEngine_GetFlags_Call struct {
	*mock.Call
}

// GetFlags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDataEngine_Expecter) GetFlags(ctx interface{}) *MockDataEngine_GetFlags_Call {
	return &MockDataEngine_GetFlags_Call{Call: _e.mock.On("GetFlags", ctx)}
}

func (_c *MockDataEngine_GetFlags_Call) Run(run func(ctx context.Context)) *MockDataEngine_GetFlags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDataEngine_GetFlags_Call) Return(_a0 []*data.FeatureFlag, _a1 error) *MockDataEngine_GetFlags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDataEngine_GetFlags_Call) RunAndReturn(run func(context.Context) ([]*data.FeatureFlag, error)) *MockDataEngine_GetFlags_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFlag provides a mock function with given fields: ctx, flag
func (_m *MockDataEngine) UpdateFlag(ctx context.Context, flag *data.FeatureFlag) error {
	ret := _m.Called(ctx, flag)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFlag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *data.FeatureFlag) error); ok {
		r0 = rf(ctx, flag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDataEngine_UpdateFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFlag'
type MockDataEngine_UpdateFlag_Call struct {
	*mock.Call
}

// UpdateFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - flag *data.FeatureFlag
func (_e *MockDataEngine_Expecter) UpdateFlag(ctx interface{}, flag interface{}) *MockDataEngine_UpdateFlag_Call {
	return &MockDataEngine_UpdateFlag_Call{Call: _e.mock.On("UpdateFlag", ctx, flag)}
}

func (_c *MockDataEngine_UpdateFlag_Call) Run(run func(ctx context.Context, flag *data.FeatureFlag)) *MockDataEngine_UpdateFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*data.FeatureFlag))
	})
	return _c
}

func (_c *MockDataEngine_UpdateFlag_Call) Return(_a0 error) *MockDataEngine_UpdateFlag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDataEngine_UpdateFlag_Call) RunAndReturn(run func(context.Context, *data.FeatureFlag) error) *MockDataEngine_UpdateFlag_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDataEngine creates a new instance of MockDataEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDataEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDataEngine {
	mock := &MockDataEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
