// Code generated by mockery v2.53.6. DO NOT EDIT.

package data

import (
	context "context"

	data "github.com/nojyerac/semaphore/data"
	mock "github.com/stretchr/testify/mock"
)

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

type MockSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSource) EXPECT() *MockSource_Expecter {
	return &MockSource_Expecter{mock: &_m.Mock}
}

// CreateFlag provides a mock function with given fields: ctx, flag
func (_m *MockSource) CreateFlag(ctx context.Context, flag *data.FeatureFlag) (string, error) {
	ret := _m.Called(ctx, flag)

	if len(ret) == 0 {
		panic("no return value specified for CreateFlag")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *data.FeatureFlag) (string, error)); ok {
		return rf(ctx, flag)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *data.FeatureFlag) string); ok {
		r0 = rf(ctx, flag)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *data.FeatureFlag) error); ok {
		r1 = rf(ctx, flag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSource_CreateFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFlag'
type MockSource_CreateFlag_Call struct {
	*mock.Call
}

// CreateFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - flag *data.FeatureFlag
func (_e *MockSource_Expecter) CreateFlag(ctx interface{}, flag interface{}) *MockSource_CreateFlag_Call {
	return &MockSource_CreateFlag_Call{Call: _e.mock.On("CreateFlag", ctx, flag)}
}

func (_c *MockSource_CreateFlag_Call) Run(run func(ctx context.Context, flag *data.FeatureFlag)) *MockSource_CreateFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*data.FeatureFlag))
	})
	return _c
}

func (_c *MockSource_CreateFlag_Call) Return(_a0 string, _a1 error) *MockSource_CreateFlag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSource_CreateFlag_Call) RunAndReturn(run func(context.Context, *data.FeatureFlag) (string, error)) *MockSource_CreateFlag_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFlag provides a mock function with given fields: ctx, id
func (_m *MockSource) DeleteFlag(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFlag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSource_DeleteFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFlag'
type MockSource_DeleteFlag_Call struct {
	*mock.Call
}

// DeleteFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSource_Expecter) DeleteFlag(ctx interface{}, id interface{}) *MockSource_DeleteFlag_Call {
	return &MockSource_DeleteFlag_Call{Call: _e.mock.On("DeleteFlag", ctx, id)}
}

func (_c *MockSource_DeleteFlag_Call) Run(run func(ctx context.Context, id string)) *MockSource_DeleteFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSource_DeleteFlag_Call) Return(_a0 error) *MockSource_DeleteFlag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSource_DeleteFlag_Call) RunAndReturn(run func(context.Context, string) error) *MockSource_DeleteFlag_Call {
	_c.Call.Return(run)
	return _c
}

// EvaluateFlag provides a mock function with given fields: ctx, flagID, userID
func (_m *MockSource) EvaluateFlag(ctx context.Context, flagID string, userID string) (bool, error) {
	ret := _m.Called(ctx, flagID, userID)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateFlag")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, flagID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, flagID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, flagID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSource_EvaluateFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluateFlag'
type MockSource_EvaluateFlag_Call struct {
	*mock.Call
}

// EvaluateFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - flagID string
//   - userID string
func (_e *MockSource_Expecter) EvaluateFlag(ctx interface{}, flagID interface{}, userID interface{}) *MockSource_EvaluateFlag_Call {
	return &MockSource_EvaluateFlag_Call{Call: _e.mock.On("EvaluateFlag", ctx, flagID, userID)}
}

func (_c *MockSource_EvaluateFlag_Call) Run(run func(ctx context.Context, flagID string, userID string)) *MockSource_EvaluateFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSource_EvaluateFlag_Call) Return(_a0 bool, _a1 error) *MockSource_EvaluateFlag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSource_EvaluateFlag_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockSource_EvaluateFlag_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuditLogs provides a mock function with given fields: ctx, flagID
func (_m *MockSource) GetAuditLogs(ctx context.Context, flagID string) ([]data.AuditLog, error) {
	ret := _m.Called(ctx, flagID)

	if len(ret) == 0 {
		panic("no return value specified for GetAuditLogs")
	}

	var r0 []data.AuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]data.AuditLog, error)); ok {
		return rf(ctx, flagID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []data.AuditLog); ok {
		r0 = rf(ctx, flagID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]data.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, flagID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSource_GetAuditLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuditLogs'
type MockSource_GetAuditLogs_Call struct {
	*mock.Call
}

// GetAuditLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - flagID string
func (_e *MockSource_Expecter) GetAuditLogs(ctx interface{}, flagID interface{}) *MockSource_GetAuditLogs_Call {
	return &MockSource_GetAuditLogs_Call{Call: _e.mock.On("GetAuditLogs", ctx, flagID)}
}

func (_c *MockSource_GetAuditLogs_Call) Run(run func(ctx context.Context, flagID string)) *MockSource_GetAuditLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSource_GetAuditLogs_Call) Return(_a0 []data.AuditLog, _a1 error) *MockSource_GetAuditLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSource_GetAuditLogs_Call) RunAndReturn(run func(context.Context, string) ([]data.AuditLog, error)) *MockSource_GetAuditLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlagByID provides a mock function with given fields: ctx, id
func (_m *MockSource) GetFlagByID(ctx context.Context, id string) (*data.FeatureFlag, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFlagByID")
	}

	var r0 *data.FeatureFlag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*data.FeatureFlag, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *data.FeatureFlag); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.FeatureFlag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSource_GetFlagByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlagByID'
type MockSource_GetFlagByID_Call struct {
	*mock.Call
}

// GetFlagByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSource_Expecter) GetFlagByID(ctx interface{}, id interface{}) *MockSource_GetFlagByID_Call {
	return &MockSource_GetFlagByID_Call{Call: _e.mock.On("GetFlagByID", ctx, id)}
}

func (_c *MockSource_GetFlagByID_Call) Run(run func(ctx context.Context, id string)) *MockSource_GetFlagByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSource_GetFlagByID_Call) Return(_a0 *data.FeatureFlag, _a1 error) *MockSource_GetFlagByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSource_GetFlagByID_Call) RunAndReturn(run func(context.Context, string) (*data.FeatureFlag, error)) *MockSource_GetFlagByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlags provides a mock function with given fields: ctx
func (_m *MockSource) GetFlags(ctx context.Context) ([]*data.FeatureFlag, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFlags")
	}

	var r0 []*data.FeatureFlag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*data.FeatureFlag, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*data.FeatureFlag); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*data.FeatureFlag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSource_GetFlags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlags'
type MockSource_GetFlags_Call struct {
	*mock.Call
}

// GetFlags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSource_Expecter) GetFlags(ctx interface{}) *MockSource_GetFlags_Call {
	return &MockSource_GetFlags_Call{Call: _e.mock.On("GetFlags", ctx)}
}

func (_c *MockSource_GetFlags_Call) Run(run func(ctx context.Context)) *MockSource_GetFlags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSource_GetFlags_Call) Return(_a0 []*data.FeatureFlag, _a1 error) *MockSource_GetFlags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSource_GetFlags_Call) RunAndReturn(run func(context.Context) ([]*data.FeatureFlag, error)) *MockSource_GetFlags_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFlag provides a mock function with given fields: ctx, flag
func (_m *MockSource) UpdateFlag(ctx context.Context, flag *data.FeatureFlag) error {
	ret := _m.Called(ctx, flag)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFlag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *data.FeatureFlag) error); ok {
		r0 = rf(ctx, flag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSource_UpdateFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFlag'
type MockSource_UpdateFlag_Call struct {
	*mock.Call
}

// UpdateFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - flag *data.FeatureFlag
func (_e *MockSource_Expecter) UpdateFlag(ctx interface{}, flag interface{}) *MockSource_UpdateFlag_Call {
	return &MockSource_UpdateFlag_Call{Call: _e.mock.On("UpdateFlag", ctx, flag)}
}

func (_c *MockSource_UpdateFlag_Call) Run(run func(ctx context.Context, flag *data.FeatureFlag)) *MockSource_UpdateFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*data.FeatureFlag))
	})
	return _c
}

func (_c *MockSource_UpdateFlag_Call) Return(_a0 error) *MockSource_UpdateFlag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSource_UpdateFlag_Call) RunAndReturn(run func(context.Context, *data.FeatureFlag) error) *MockSource_UpdateFlag_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSource creates a new instance of MockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSource {
	mock := &MockSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
