// Code generated by mockery v2.53.6. DO NOT EDIT.

package data

import (
	context "context"

	data "github.com/nojyerac/semaphore/data"
	mock "github.com/stretchr/testify/mock"
)

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

type MockSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSource) EXPECT() *MockSource_Expecter {
	return &MockSource_Expecter{mock: &_m.Mock}
}

// GetFlags provides a mock function with given fields: ctx
func (_m *MockSource) GetFlags(ctx context.Context) ([]data.Flag, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFlags")
	}

	var r0 []data.Flag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]data.Flag, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []data.Flag); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]data.Flag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSource_GetFlags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlags'
type MockSource_GetFlags_Call struct {
	*mock.Call
}

// GetFlags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSource_Expecter) GetFlags(ctx interface{}) *MockSource_GetFlags_Call {
	return &MockSource_GetFlags_Call{Call: _e.mock.On("GetFlags", ctx)}
}

func (_c *MockSource_GetFlags_Call) Run(run func(ctx context.Context)) *MockSource_GetFlags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSource_GetFlags_Call) Return(_a0 []data.Flag, _a1 error) *MockSource_GetFlags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSource_GetFlags_Call) RunAndReturn(run func(context.Context) ([]data.Flag, error)) *MockSource_GetFlags_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSource creates a new instance of MockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSource {
	mock := &MockSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
