// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: flag.proto

package flag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFlagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlagRequest) Reset() {
	*x = GetFlagRequest{}
	mi := &file_flag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlagRequest) ProtoMessage() {}

func (x *GetFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlagRequest.ProtoReflect.Descriptor instead.
func (*GetFlagRequest) Descriptor() ([]byte, []int) {
	return file_flag_proto_rawDescGZIP(), []int{0}
}

func (x *GetFlagRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetFlagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         *Flag                  `protobuf:"bytes,1,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlagResponse) Reset() {
	*x = GetFlagResponse{}
	mi := &file_flag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlagResponse) ProtoMessage() {}

func (x *GetFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlagResponse.ProtoReflect.Descriptor instead.
func (*GetFlagResponse) Descriptor() ([]byte, []int) {
	return file_flag_proto_rawDescGZIP(), []int{1}
}

func (x *GetFlagResponse) GetFlags() *Flag {
	if x != nil {
		return x.Flags
	}
	return nil
}

type StreamFlagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFlagsRequest) Reset() {
	*x = StreamFlagsRequest{}
	mi := &file_flag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFlagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFlagsRequest) ProtoMessage() {}

func (x *StreamFlagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFlagsRequest.ProtoReflect.Descriptor instead.
func (*StreamFlagsRequest) Descriptor() ([]byte, []int) {
	return file_flag_proto_rawDescGZIP(), []int{2}
}

type StreamFlagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         *Flag                  `protobuf:"bytes,1,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFlagsResponse) Reset() {
	*x = StreamFlagsResponse{}
	mi := &file_flag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFlagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFlagsResponse) ProtoMessage() {}

func (x *StreamFlagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFlagsResponse.ProtoReflect.Descriptor instead.
func (*StreamFlagsResponse) Descriptor() ([]byte, []int) {
	return file_flag_proto_rawDescGZIP(), []int{3}
}

func (x *StreamFlagsResponse) GetFlags() *Flag {
	if x != nil {
		return x.Flags
	}
	return nil
}

type Flag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flag) Reset() {
	*x = Flag{}
	mi := &file_flag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag) ProtoMessage() {}

func (x *Flag) ProtoReflect() protoreflect.Message {
	mi := &file_flag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag.ProtoReflect.Descriptor instead.
func (*Flag) Descriptor() ([]byte, []int) {
	return file_flag_proto_rawDescGZIP(), []int{4}
}

func (x *Flag) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Flag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Flag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_flag_proto protoreflect.FileDescriptor

const file_flag_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"flag.proto\x12\x04flag\" \n" +
	"\x0eGetFlagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"3\n" +
	"\x0fGetFlagResponse\x12 \n" +
	"\x05flags\x18\x01 \x01(\v2\n" +
	".flag.FlagR\x05flags\"\x14\n" +
	"\x12StreamFlagsRequest\"7\n" +
	"\x13StreamFlagsResponse\x12 \n" +
	"\x05flags\x18\x01 \x01(\v2\n" +
	".flag.FlagR\x05flags\"L\n" +
	"\x04Flag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription2\x8b\x01\n" +
	"\vFlagService\x126\n" +
	"\aGetFlag\x12\x14.flag.GetFlagRequest\x1a\x15.flag.GetFlagResponse\x12D\n" +
	"\vStreamFlags\x12\x18.flag.StreamFlagsRequest\x1a\x19.flag.StreamFlagsResponse0\x01B\tZ\apb/flagb\x06proto3"

var (
	file_flag_proto_rawDescOnce sync.Once
	file_flag_proto_rawDescData []byte
)

func file_flag_proto_rawDescGZIP() []byte {
	file_flag_proto_rawDescOnce.Do(func() {
		file_flag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flag_proto_rawDesc), len(file_flag_proto_rawDesc)))
	})
	return file_flag_proto_rawDescData
}

var file_flag_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_flag_proto_goTypes = []any{
	(*GetFlagRequest)(nil),      // 0: flag.GetFlagRequest
	(*GetFlagResponse)(nil),     // 1: flag.GetFlagResponse
	(*StreamFlagsRequest)(nil),  // 2: flag.StreamFlagsRequest
	(*StreamFlagsResponse)(nil), // 3: flag.StreamFlagsResponse
	(*Flag)(nil),                // 4: flag.Flag
}
var file_flag_proto_depIdxs = []int32{
	4, // 0: flag.GetFlagResponse.flags:type_name -> flag.Flag
	4, // 1: flag.StreamFlagsResponse.flags:type_name -> flag.Flag
	0, // 2: flag.FlagService.GetFlag:input_type -> flag.GetFlagRequest
	2, // 3: flag.FlagService.StreamFlags:input_type -> flag.StreamFlagsRequest
	1, // 4: flag.FlagService.GetFlag:output_type -> flag.GetFlagResponse
	3, // 5: flag.FlagService.StreamFlags:output_type -> flag.StreamFlagsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_flag_proto_init() }
func file_flag_proto_init() {
	if File_flag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flag_proto_rawDesc), len(file_flag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flag_proto_goTypes,
		DependencyIndexes: file_flag_proto_depIdxs,
		MessageInfos:      file_flag_proto_msgTypes,
	}.Build()
	File_flag_proto = out.File
	file_flag_proto_goTypes = nil
	file_flag_proto_depIdxs = nil
}
