// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: flag.proto

package flag

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlagService_GetFlag_FullMethodName     = "/flag.FlagService/GetFlag"
	FlagService_StreamFlags_FullMethodName = "/flag.FlagService/StreamFlags"
)

// FlagServiceClient is the client API for FlagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlagServiceClient interface {
	GetFlag(ctx context.Context, in *GetFlagRequest, opts ...grpc.CallOption) (*GetFlagResponse, error)
	StreamFlags(ctx context.Context, in *StreamFlagsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamFlagsResponse], error)
}

type flagServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlagServiceClient(cc grpc.ClientConnInterface) FlagServiceClient {
	return &flagServiceClient{cc}
}

func (c *flagServiceClient) GetFlag(ctx context.Context, in *GetFlagRequest, opts ...grpc.CallOption) (*GetFlagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFlagResponse)
	err := c.cc.Invoke(ctx, FlagService_GetFlag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flagServiceClient) StreamFlags(ctx context.Context, in *StreamFlagsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamFlagsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FlagService_ServiceDesc.Streams[0], FlagService_StreamFlags_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamFlagsRequest, StreamFlagsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlagService_StreamFlagsClient = grpc.ServerStreamingClient[StreamFlagsResponse]

// FlagServiceServer is the server API for FlagService service.
// All implementations must embed UnimplementedFlagServiceServer
// for forward compatibility.
type FlagServiceServer interface {
	GetFlag(context.Context, *GetFlagRequest) (*GetFlagResponse, error)
	StreamFlags(*StreamFlagsRequest, grpc.ServerStreamingServer[StreamFlagsResponse]) error
	mustEmbedUnimplementedFlagServiceServer()
}

// UnimplementedFlagServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlagServiceServer struct{}

func (UnimplementedFlagServiceServer) GetFlag(context.Context, *GetFlagRequest) (*GetFlagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFlag not implemented")
}
func (UnimplementedFlagServiceServer) StreamFlags(*StreamFlagsRequest, grpc.ServerStreamingServer[StreamFlagsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamFlags not implemented")
}
func (UnimplementedFlagServiceServer) mustEmbedUnimplementedFlagServiceServer() {}
func (UnimplementedFlagServiceServer) testEmbeddedByValue()                     {}

// UnsafeFlagServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlagServiceServer will
// result in compilation errors.
type UnsafeFlagServiceServer interface {
	mustEmbedUnimplementedFlagServiceServer()
}

func RegisterFlagServiceServer(s grpc.ServiceRegistrar, srv FlagServiceServer) {
	// If the following call panics, it indicates UnimplementedFlagServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlagService_ServiceDesc, srv)
}

func _FlagService_GetFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlagServiceServer).GetFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlagService_GetFlag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlagServiceServer).GetFlag(ctx, req.(*GetFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlagService_StreamFlags_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamFlagsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FlagServiceServer).StreamFlags(m, &grpc.GenericServerStream[StreamFlagsRequest, StreamFlagsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlagService_StreamFlagsServer = grpc.ServerStreamingServer[StreamFlagsResponse]

// FlagService_ServiceDesc is the grpc.ServiceDesc for FlagService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlagService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flag.FlagService",
	HandlerType: (*FlagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFlag",
			Handler:    _FlagService_GetFlag_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFlags",
			Handler:       _FlagService_StreamFlags_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "flag.proto",
}
